name: realestate
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  marquee: ^2.3.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.0.0+2
  svg_image: ^0.0.5
  theme_provider: ^0.6.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/colorkit.jpg"

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/static/Cairo-Black.ttf

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
