// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeuJfqKK3jQHstNmB0JQbEI0BEXG-DINs',
    appId: '1:356056297971:web:a9950beebd52b1d7bf6286',
    messagingSenderId: '356056297971',
    projectId: 'flutter-test-e583c',
    authDomain: 'flutter-test-e583c.firebaseapp.com',
    databaseURL: 'https://flutter-test-e583c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-e583c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgGPP8IUkYOMJAymzFv10dA4lLAr1d-8',
    appId: '1:356056297971:android:ef95691ffc54aa7bbf6286',
    messagingSenderId: '356056297971',
    projectId: 'flutter-test-e583c',
    databaseURL: 'https://flutter-test-e583c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-e583c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGGzEOXkdnIS-9KjLKDr3rJJuxPcwOog',
    appId: '1:356056297971:ios:0596566a8f4060b2bf6286',
    messagingSenderId: '356056297971',
    projectId: 'flutter-test-e583c',
    databaseURL: 'https://flutter-test-e583c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-e583c.firebasestorage.app',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfGGzEOXkdnIS-9KjLKDr3rJJuxPcwOog',
    appId: '1:356056297971:ios:0596566a8f4060b2bf6286',
    messagingSenderId: '356056297971',
    projectId: 'flutter-test-e583c',
    databaseURL: 'https://flutter-test-e583c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-e583c.firebasestorage.app',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeuJfqKK3jQHstNmB0JQbEI0BEXG-DINs',
    appId: '1:356056297971:web:66b26b41a0ea39ddbf6286',
    messagingSenderId: '356056297971',
    projectId: 'flutter-test-e583c',
    authDomain: 'flutter-test-e583c.firebaseapp.com',
    databaseURL: 'https://flutter-test-e583c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-e583c.firebasestorage.app',
  );

}